# Use an official Node.js runtime as a parent image
FROM node:18

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package*.json /app/

# Install dependencies
RUN npm install

COPY . .

COPY dockerenv.js ./src/constants.js

# Copy the rest of the application code
#COPY . /app

RUN npm run build

# Expose the frontend port
EXPOSE 3000

# Run the application
CMD ["npm", "start"]