---
## This is a mindmap mermaid diagram showing the different use cases for a user using the FairShare app
---
mindmap
  root((FairShare Application))
    User
      Sign Up
      Log In
      Log Out
      Send Friend Request
      Accept Friend Request
      Decline Friend Request
      Create Group
      View Groups
      Create Expense
      View Expenses
      View Balances
      Settle Payment
      View Overview
      View Top Categories