name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - 'GCP-deployment'

env:
  PROJECT_ID: 'atomic-hash-455114-v1' # TODO: update to your Google Cloud project ID
  REGION: 'us-central1' # TODO: update to your region
  SERVICE: 'fairshare-backend-service' # TODO: update to your service name

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    permissions:
      contents: 'read'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - name: 'Set up Google Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: 'latest'
          project_id: '${{ env.PROJECT_ID }}'
          service_account_key: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Authenticate to Google Cloud'
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" > "${HOME}/gcloud-service-key.json"
          gcloud auth activate-service-account --key-file="${HOME}/gcloud-service-key.json"

      - name: 'Docker Auth'
        uses: 'docker/login-action@v3'
        with:
          username: 'oauth2accesstoken'
          password: '${{ secrets.GCP_SA_KEY }}'
          registry: '${{ env.REGION }}-docker.pkg.dev'

      - name: 'Build and Push Container'
        run: |-
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}"
          docker build --tag "${DOCKER_TAG}" .
          docker push "${DOCKER_TAG}"

      - name: 'Deploy to Cloud Run'
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: '${{ env.SERVICE }}'
          region: '${{ env.REGION }}'
          image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}'

      - name: 'Show output'
        run: echo ${{ steps.deploy.outputs.url }}